language: generic
sudo: false

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1414"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
  matrix:
    - TEST=CODE
    - TEST=WEB
    - TEST=MAP MAP_PATH=example
    - TEST=MAP MAP_PATH=exodus
    - TEST=MAP MAP_PATH=torch
    - TEST=MAP MAP_PATH=utopia
    - TEST=MAP MAP_PATH=dreyfus

cache:
  directories:
    - tgui/node_modules
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

script:
  - test/run-test.sh
